### ISSUE TITLE
Taiwan Rust Community Logo

### ISSUE THREAD

**Issue by wildskyf** [rustlangtw/rustlangtw.github.io#3]
from #2 :
> 這似乎更不重要了XD 不過能有一個代表臺灣又 rusty 的 Logo，大家應該都很贊成吧？

**Comment by tigercosmos** [comment]
是沒意見啦 我覺得 輪子 + 熊讚 很不錯
效果大概就像 servo 那樣

**Comment by kanru** [comment]
有 logo 了 -- https://github.com/rust-tw/media/tree/master/logos

![Rust Taiwan](https://raw.githubusercontent.com/rust-tw/media/master/logos/rust-taiwan.png)
